// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfBzqq_cNJfGsiRKVKrc3uDQjH36E27o',
    appId: '1:1055120878021:web:d9b02e5c5ca36d1fc583ac',
    messagingSenderId: '1055120878021',
    projectId: 'shirtyapp',
    authDomain: 'shirtyapp.firebaseapp.com',
    storageBucket: 'shirtyapp.firebasestorage.app',
    measurementId: 'G-SRJ8J91Y87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXw6zgrV-OiT6GH2ihgbV1A-O54KtwVRk',
    appId: '1:1055120878021:android:c6e90acd1a0c0720c583ac',
    messagingSenderId: '1055120878021',
    projectId: 'shirtyapp',
    storageBucket: 'shirtyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcHHpqeZihFLFInaGTFckty06Joq3kPc',
    appId: '1:1055120878021:ios:3033011d904876dac583ac',
    messagingSenderId: '1055120878021',
    projectId: 'shirtyapp',
    storageBucket: 'shirtyapp.firebasestorage.app',
    iosBundleId: 'com.example.clothshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcHHpqeZihFLFInaGTFckty06Joq3kPc',
    appId: '1:1055120878021:ios:3033011d904876dac583ac',
    messagingSenderId: '1055120878021',
    projectId: 'shirtyapp',
    storageBucket: 'shirtyapp.firebasestorage.app',
    iosBundleId: 'com.example.clothshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfBzqq_cNJfGsiRKVKrc3uDQjH36E27o',
    appId: '1:1055120878021:web:e6affb1b75338a43c583ac',
    messagingSenderId: '1055120878021',
    projectId: 'shirtyapp',
    authDomain: 'shirtyapp.firebaseapp.com',
    storageBucket: 'shirtyapp.firebasestorage.app',
    measurementId: 'G-JXFDF7E8TQ',
  );
}
